name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_macros:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish release of googletest_macro
      env:
        CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
      run: cargo publish -p googletest_macro

  publish:

    needs: publish_macros
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish release of googletest
      env:
        CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
      run: cargo publish -p googletest
